<template>
  <div>
    <v-dialog v-model="show" width="700" style="z-index: 1000">
      <template v-slot:activator="{ on }">
        <v-btn block text color="secondary" class="justify-start" v-on="on">
          <v-icon>mdi-import</v-icon>
          Import layout
        </v-btn>
      </template>

      <v-card>
        <v-card-title> Import layout </v-card-title>

        <v-card-text>
          <p>
            Paste the C++ header file generated by this designer into the area
            below.
          </p>
          <v-textarea
            v-model="value"
            outlined
            label="Paste your layout.h here"
            class="mb-0"
            height="200px"
            :error-messages="error"
            autofocus
            no-resize
          />
        </v-card-text>
      </v-card>
    </v-dialog>
  </div>
</template>

<script>
import * as CppGen from '~/src/layoutgen/Cpp'
import * as TsGen from '~/src/layoutgen/Typescript'

export default {
  props: {},
  data() {
    return {
      show: false,
      value: '',
      error: ''
    }
  },
  watch: {
    show(on) {
      if (on) {
        this.value = ''
      }
    },
    value(val) {
      this.error = ''
      if (val === '') return

      const layout = CppGen.parse(val) || TsGen.parse(val)
      if (layout === null) {
        this.error = 'Failed to parse the layout!'
      } else {
        this.show = false
        this.$emit('import-layout', layout)

        this.$notify({
          group: 'success',
          title: 'Layout imported',
          text:
            'The layout was successfully imported. You can press ctrl+Z to undo.'
        })
      }
    }
  },
  methods: {}
}
</script>

<style lang="scss" scoped></style>
