name: Github pages deploy
on:
  push:
    branches: [master]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install
        uses: actions/setup-node@v3
        with:
          node-version: 12
          cache: 'yarn'
      - run: yarn install
      - run: yarn generate
        env:
          NUXT_SUBFOLDER: /Esp32-RBGridUI-Designer/
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
